<?php

/**
 * @file
 * Contains otp_verify module.
 */

use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function otp_verify_entity_insert(EntityInterface $entity) {
  $verification_code_service = \Drupal::service('otp_verify.verification_code');
  $otp_verify_service = \Drupal::service('otp_verify.gateway');
  if ($entity->getEntityTypeId() === 'user' && !$verification_code_service->isVerified($entity->id())) {
    $entity->block();
    $transaction = \Drupal::database()->startTransaction();
    try {
      // Generate otp code.
      $code = $verification_code_service->storeCodeInDataBase($entity->id());
      // Get verification message.
      $message = $verification_code_service->getVerificationMessage($code);
      $phone = $entity->field_phone->getString();
      // Send sms message.
      $otp_verify_service->sendSmsMessage($phone, $message);
      // Redirect to verify form.
      $redirect = new RedirectResponse(Url::fromRoute('otp_verify.otp_form')->toString());
      $redirect->send();
    }
    catch (\Exception $ex) {
      $transaction->rollBack();
      \Drupal::messenger()->addError($ex->getMessage());
    }
    unset($transaction);
  }
}
